language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - oraclejdk12
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

script: javac -cp "lib/*" -d bin $(find . -name "*.java")