language: java
jdk:
  - oraclejdk9
  - oraclejdk11
  - oraclejdk12
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

script: javac -cp "lib/*:src" -d bin src/rts/MicroRTS.java

# java -cp "lib/*:bin" rts.MicroRTS